import { Inter } from "next/font/google";
import "./globals.css";
import "./Sass/abstracts/_forms.scss";
import "./Sass/abstracts/_buttons.scss";
import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>{children}</body>
      </SessionProvider>
    </html>
  );
}
